### ISSUE TITLE
Define StateHandler Behavior for all mechanisms

### ISSUE THREAD

**Issue by gavinskycastle** [4201VitruvianBots/ChargedUp2023#199]
StateHandler:
- [ ] Mechanism setpoints should not be directly tied to superstructure states (e.g. Any combination of ELEVATOR_HIGH setpoint and then using the ELEVATOR_JOYSTICK should generally put the superstructure into the HIGH state, unless you pass one of the state thresholds).
- [ ] State machine will always set lower/upper limits on all mechanisms when first entering the state.
- [ ] To make things more smooth, have linear-interpreted (LERP) min/max limits (optional)

- [ ] advanceState():
-Check current state against desired state.
-Enforce safe limits to before advancing states.

- [ ] STOWED:
-Default state if no command is given or if STOWED button is pressed
-Hard limit wrist min/max angles to WRIST_STOWED_UPPER_LIMIT and WRIST_STOWED_UPPER_LIMIT (Make this a linear interpolation?)
-Elevator should have full height range
-Can only go to INTAKE or LOW from here

- [ ] INTAKE GROUND:
-Enters when Intake/Outtake Button is pressed and if Elevator is in LOW/STOWED/INTAKE state
-Elevator will be commanded to GROUND position and cannot move up
-Intake will be commanded to INTAKE position
-Exit when Intake/Outtake Button is no longer pressed

- [ ] INTAKE SUBSTATION:
- 

- [ ] LOW:
-When elevator is commanded to a setpoint above the LOW_TO_HIGH_THRESHOLD if previous state was STOWED/INTAKE/JOYSTICK or if setpoint is below the HIGH_TO_LOW_THRESHOLD when previous state is HIGH
-Hard limit wrist min/max angles to WRIST_LOW_UPPER_LIMIT and WRIST_LOW_UPPER_LIMIT
-Elevator should have full height range

-Move to HIGH if elevator is above LOW_TO_HIGH_THRESHOLD
-Move to STOWED if elevator is below LOW_STATE_LOWER_THRESHOLD

- [ ] HIGH:
-When elevator is commanded to a setpoint above the LOW_TO_HIGH_THRESHOLD if previous state was LOW or if setpoint is below the EXTENDED_TO_HIGH_THRESHOLD when previous state is HIGH
-Hard limit wrist min/max angles to WRIST_HIGH_LOWER_LIMIT, WRIST_HIGH_UPPER_LIMIT
-Elevator should have a min height limit ELEVATOR_HIGH_LOWER_LIMIT
-Swerve should max speed to SWERVE_HIGH_LIMIT

-Move to EXTENDED if elevator is above HIGH_TO_EXTENDED_THRESHOLD and wrist is above WRIST_EXTENDED_LOWER_LIMIT
-Move to LOW if elevator is below HIGH_TO_LOW_THRESHOLD and wrist is below WRIST_LOW_UPPER_LIMIT. If wrist is not below WRIST_LOW_UPPER_LIMIT, command wrist to a setpoint below WRIST_LOW_UPPER_LIMIT

- [ ] EXTENDED:
-When elevator is commanded to a setpoint above the EXTENDED_TO_HIGH_THRESHOLD if previous state was HIGH
-Hard limit wrist min/max angles to WRIST_EXTENDED_LOWER_LIMIT, WRIST_EXTENDED_UPPER_LIMIT
-Elevator should have a min height limit ELEVATOR_EXTENDED_LOWER_LIMIT
-Swerve should max speed to SWERVE_EXTENDED_LIMIT

-Move to HIGH if elevator is below the EXTENDED_TO_HIGH_THRESHOLD and wrist is below the WRIST_HIGH_UPPER_LIMIT. If wrist is not below WRIST_HIGH_UPPER_LIMIT, command wrist to a setpoint below WRIST_HIGH_UPPER_LIMIT

**Comment by gavinskycastle** [comment]
This still has not been done yet

**Comment by jonathandao0** [comment]
Revised this to match current understanding of StateHandler.

**Comment by AndrewKempen** [comment]
Why do we set limits for the wrist when it is in the stowed state? Shouldn't we just set the wrist to the stowed angle?

I think limits for the wrist should be set as a simple function of where the elevator is. When the elevator is below the threshold height, we should set the up and down limits to the below threshold limits and when the elevator is above the threshold we can expand the wrist limits.

**Comment by AndrewKempen** [comment]
I think we also want to have states that control the transition of the elevator through the threshold point. We should have a LOW_TRANSIT and a HIGH_TRANSIT state that we enter whenever we aren't in a predefined wrist and elevator state. These states will have logic that looks at our desired state and appropriately attempts to move the elevator and four bar to the desired state unless it requires  going through the threshold point in which case it would block transition to the opposite TRANSIT state untill wrist and elevator have moved to angles that are safe for crossing the threshold height.
