### ISSUE TITLE
Add additional shuffleboard values

### ISSUE THREAD

**Issue by SherazF** [4201VitruvianBots/ChargedUp2023#213]
Current ideas:

- [x] Elevator height converted to inches
- [ ] Detected robot based off mac address
- Possible values:
    - Gridlock/Alpha
    - Rush Hour/Beta
    - Unknown
    - Simulation

All SmartDashboard/Shuffleboard implementation should follow the new NetworkTables 4 API (https://docs.wpilib.org/en/stable/docs/software/networktables/nt4-migration-guide.html). Using the old NetworkTables 3 APIs seem to be less stable, where values on SmartDashboard/Shuffleboard/Glass will sometimes not update after redeploying code or disconnecting/reconnecting the robot.

**Comment by gavinskycastle** [comment]
Tasks moved to #216
