### ISSUE TITLE
Tuning JustBalance

### ISSUE THREAD

**Issue by SherazF** [4201VitruvianBots/ChargedUp2023#281]
- [x] Verify that path is getting onto charging station
- [ ] Robot is trying to balance 
- [ ] Robot stops balancing after 3 seconds

**Comment by jonathandao0** [comment]
https://www.chiefdelphi.com/t/psa-balance-in-auto/429778
https://www.chiefdelphi.com/t/what-is-your-approach-to-automate-charging-station-balancing/427432/4
https://www.chiefdelphi.com/t/warning-to-everyone-working-on-auto-balance/422460
