### ISSUE TITLE
Refactor Wrist Subsystem

### ISSUE THREAD

**Issue by jonathandao0** [4201VitruvianBots/ChargedUp2023#294]
- [x] Move most/all constants to Constants.java
- [x] Remove Duplicate/Unnecessary functions/variables
- [x] Simply logic
- [x] Add comments to functions
- [x] Address all TODOs in the subsystem/subsystem commands

Wrist Subsystem Specifics
- Adjust Wrist Trapezoid Profile (Fast should be slightly slower; Initial acceleration should be fast, but slowing down should be slower)
- Seperate setpoints for cube vs cone ground intaking (Cone setpoint should be slightly higher)
- Add Wrist Mechanism2d simulation

Code must be reviewed and approved by mentor before merging to main

**Comment by gavinskycastle** [comment]
Beach cities issue number!
