### ISSUE TITLE
Second Order Kinematics Swerve Library

### ISSUE THREAD

**Issue by SherazF** [4201VitruvianBots/ChargedUp2023#366]
Whitepaper: https://www.chiefdelphi.com/t/whitepaper-swerve-drive-skew-and-second-order-kinematics/416964

Chiefdelphi post on the library (Yet Another Generic Swerve Library): https://www.chiefdelphi.com/t/yet-another-generic-swerve-library-yagsl-beta/425148

- [x] Get overview from whitepaper
- [x] Clone repo and test code on our drivetrain
- [x] Change constants as needed
- [x] Implement into our robot code

**Comment by jonathandao0** [comment]
Test this alternative to YAGSL:
https://github.com/wpilibsuite/allwpilib/issues/5349
